### ISSUE TITLE
Make result table sortable by firstname or lastname

### ISSUE THREAD

**Issue by Lefaux** [Lefaux/guestlist#19]
Tapping onto the column-header should sort the table either by `firstname ASC` or `lastname ASC`.
Other sorting orders are not necessary.

**Comment by andreaskienast** [comment]
Which one should be the default sorting, as this affects the initial ordering via PHP as well?
I would like to research which library fits the needs the most, as there may be performance issues with large datasets, which will be easily notable on mid-end devices like an iPad Air.

I estimate this task will take roughly 2 hours.

**Comment by Lefaux** [comment]
DefaultSort: Firstname ASC, Lastname ASC
We won't be having datasets bigger than 40 lines for now.
