### ISSUE TITLE
Add possibility to mark guest as no-show

### ISSUE THREAD

**Issue by Lefaux** [Lefaux/guestlist#22]
At the moment we calculate noShows just by counting the pluses that did not arrive with the primary guest.
We need to be able to mark guests as noShows when we know in advance, that they will not show up.

Technically we should add a new property to the Guest entity called `checkInStatus` which can take the values of 
* Open
* Checked In
* Checked In with NoShows
* Cancelled participation

**Comment by andreaskienast** [comment]
"Checked In with NoShows" sounds like a computed status to me, as we're still storing the amount of "no shows", right?

I'd do the following:
- add an enum class (CheckInStatus.php or alike)
- adjust the existing `Guest` entity
- database migration
- endpoint adjustment
- adjust templates and JavaScript

I think this will take roundabout **1h**.
